<?xml version="1.0"?>

<robot name="sdvt_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <property name="base_x_size" value="3" />
  <property name="base_y_size" value="2" />
  <property name="base_z_size" value="1" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="1.702" />
  <xacro:property name="track" value="1.016" />
  <xacro:property name="wheel_vertical_offset" value="-0.05" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.23" />
  <xacro:property name="wheel_radius" value="0.242" />

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0.559 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="package://sdvt_description/meshes/New Frame with car no wheels meters.stl" scale="0.0104 0.0104 0.0104"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sdvt_description/meshes/New Frame with car no wheels meters.stl" scale="0.0104 0.0104 0.0104"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="33.455" />
        <origin xyz="-0.08748 -0.00085 0.09947" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="$(optenv HUSKY_IMU_XYZ 0.19 0 0.149)" rpy="$(optenv HUSKY_IMU_RPY 0 -1.5708 3.1416)" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
    </gazebo>

    <!-- SDVT wheel xacro -->
	<xacro:macro name="sdvt_wheel" params="wheel_prefix *joint_pose">
		<link name="${wheel_prefix}_wheel_link">
			<inertial>
				<mass value="2.637" />
				<origin xyz="0 0 0" />
				<inertia  ixx="0.02467" ixy="0" ixz="0" iyy="0.02467" iyz="0" izz="0.04411" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} ${M_PI/2} 0" />
				<geometry>
					 <mesh filename="package://sdvt_description/meshes/tire meters.stl" scale="0.104 0.104 0.104"/> 
 					 <!--<cylinder length="${wheel_length}" radius="${wheel_radius}" /> -->
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} ${M_PI/2} 0" />
				<geometry>
					 <mesh filename="package://sdvt_description/meshes/tire meters.stl" scale="0.0104 0.0104 0.0104"/> 
 					<!-- <cylinder length="${wheel_length}" radius="${wheel_radius}" />-->
				</geometry>
			</collision>
		</link>

		<gazebo reference="${wheel_prefix}_wheel_link">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

		<joint name="${wheel_prefix}_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${wheel_prefix}_wheel_link"/>
			<xacro:insert_block name="joint_pose"/>
			<axis xyz="0 1 0" rpy="0 0 0" />
		</joint>

		<transmission name="${wheel_prefix}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${wheel_prefix}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="${wheel_prefix}_wheel">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>

	</xacro:macro>

    <!-- SDVT wheel macros -->
    <xacro:sdvt_wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sdvt_wheel>
    <xacro:sdvt_wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sdvt_wheel>
    <xacro:sdvt_wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sdvt_wheel>
    <xacro:sdvt_wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:sdvt_wheel>

  <!-- Decoration description  <xacro:sdvt_decorate /> -->

  <!-- Same note as applies to imu_link -->
  <link name="navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
    <parent link="base_link" />
    <child link="navsat_link" />
    <origin xyz="-0.180 0.126 0.1815" />
  </joint>

  <!-- Front radar -->
<link name="Radar">
    <visual>
      <geometry>
        <box size=".1 .23 .14"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size=".1 .23 .14"/>
      </geometry>
    </collision>
</link>
 <joint name="base_to_radar" type="fixed">
      <child link ="Radar" />
      <parent link ="base_link" />
      <origin xyz="1.18 0 0.2"/>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>

  <!-- Left lidar -->

  <link name="lidar_left_link">
<!--<inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
               iyy="0.001"  iyz="0.0"
               izz="0.001" />
    </inertial> -->
     <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <geometry>
        <cylinder length="0.09" radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

    <joint name="hokuyo_joint_left" type="fixed">
      <child link ="lidar_left_link" />
      <parent link ="base_link" />
      <origin xyz="-0.11 -0.65 0.12"/>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>

  <!-- Right lidar -->
 <link name="lidar_right">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <geometry>
        <cylinder length="0.09" radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

    <joint name="hokuyo_joint_right" type="fixed">
      <child link ="lidar_right" />
      <parent link ="base_link" />
      <origin xyz="-0.11 0.65 0.12"/>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>

  <!-- Left camera -->
<link name="camera_l">
    <visual>
      <geometry>
        <cylinder length="0.076" radius="0.04"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.04"/>
      </geometry>
    </collision>
</link>
 <joint name="base_to_camera_l" type="fixed">
      <child link ="camera_l" />
      <parent link ="base_link" />
      <origin xyz="0.5 -0.65 1.1"/>
    </joint>

  <!-- Right camera -->
   <link name="camera_r">
    <visual>
      <geometry>
        <cylinder length="0.076" radius="0.04"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.04"/>
      </geometry>
    </collision>
</link>
 <joint name="base_to_camera_r" type="fixed">
      <child link ="camera_r" />
      <parent link ="base_link" />
      <origin xyz="0.5 0.6 1.1"/>
    </joint>

  <xacro:include filename="sdvt.gazebo" />

</robot>
